spring:
  application:
    name: Talksy
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/talksy_chat
#    username:  talksy_chat
#    password: 123
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://dpg-d2k3ha63jp1c73fosq4g-a.oregon-postgres.render.com:5432/talksy_db
      username: talksy_db_user
      password: EdtM2nvNwyH17VPtfmf7rHNVeQYQWOkp


telegram:
  bot:
    token: 8449372062:AAE9bUlVdkuEpvFALve9CGdHdxbIoPRcu-U
jwt:
  secret: "superSecretKeyForJwtSigningChangeThisToStrongKey123!"
  expiration: 3600000
logging:
  level:
    org.springframework.security: DEBUG
